from typing import Literal
import datetime as dt
from app.support import HasID, SuperImmut, SuperView
from app.style import GreigeStyle, Color, FabricStyle
from app.inventory import AllocRoll
from app.schedule import DyeLot, DyeLotView

class Bucket(SuperView['Req']):
    item: FabricStyle
    @property
    def greige(self) -> GreigeStyle: ...
    @property
    def color(self) -> Color: ...
    @property
    def lots(self) -> list[DyeLotView]: ...
    @property
    def yds(self) -> float: ...
    @property
    def lbs(self) -> float: ...
    @property
    def date(self) -> dt.datetime: ...

class Req(HasID[str], SuperImmut):
    item: FabricStyle
    def __init__(self, item: FabricStyle, p1date: dt.datetime,
                 buckets: tuple[float, float, float, float]) -> None: ...
    @property
    def _prefix(self) -> str: ...
    @property
    def id(self) -> str: ...
    @property
    def greige(self) -> GreigeStyle: ...
    @property
    def color(self) -> Color: ...
    @property
    def lots(self) -> list[DyeLotView]: ...
    def bucket(self, pnum: Literal[1, 2, 3, 4]) -> Bucket: ...
    def assign_lot(self, rolls: list[AllocRoll]) -> DyeLot: ...
    def unassign_lot(self, lot: DyeLotView) -> None: ...