from typing import TypeVar, Generic, Self, Hashable, Iterator
from abc import ABC, abstractmethod
from app.support import Viewable, HasID, HasIDLike

_T1 = TypeVar('_T1', bound=Viewable)
_T2 = TypeVar('_T2')

class Item(Generic[_T1, _T2]):
    def __init__(self) -> None: ...
    @property
    def was_inserted(self) -> bool: ...
    @property
    def is_empty(self) -> bool: ...
    @property
    def data(self) -> _T2: ...
    def __eq__(self, value: Self) -> bool: ...
    def __lt__(self, value: Self) -> bool: ...
    def store(self, val: _T1, idx: int) -> None: ...
    def empty(self) -> _T1: ...

_T3 = TypeVar('_T3', bound=HasIDLike)
_T4 = TypeVar('_T4', bound=HasID)
_T5 = TypeVar('_T5', bound=Hashable)

class BaseGroup(Generic[_T3, _T4, _T5], ABC):
    def __init__(self, init_size: int = ...) -> None: ...
    @property
    def n_items(self) -> int: ...
    def contains_id(self, item_id: _T5) -> bool: ...
    @abstractmethod
    def add(self, value: _T4) -> None: ...
    @abstractmethod
    def remove(self, item_id: _T5) -> _T4: ...
    def get_by_id(self, item_id: _T5) -> _T3: ...
    def iter_items(self) -> Iterator[_T3]: ...