import datetime as dt
from app.support import SuperImmut, DateRange
from app.schedule import Job

class JetSched(SuperImmut):
    date_rng: DateRange
    def __init__(self, min_date: dt.datetime, max_date: dt.datetime, soil_level: int) -> None: ...
    @property
    def last_job_end(self) -> dt.datetime: ...
    @property
    def rem_time(self) -> dt.timedelta: ...
    @property
    def jobs_since_strip(self) -> int: ...
    @property
    def soil_level(self) -> int: ...
    @property
    def jobs(self) -> list[Job]: ...
    def check_for_strip(self, newjob: Job) -> bool: ...
    def add_job(self, job: Job) -> None: ...
    def set_times(self) -> None: ...
    def clear_jobs(self) -> None: ...