import datetime
from app.support import HasID
from app.schedule.dyelot import DyeLot

class Job(HasID[int]):
    def __init__(self, start: datetime.datetime,
                 cycle_time: datetime.timedelta,
                 lots: tuple[DyeLot, ...] = ...) -> None: ...
    @property
    def start(self) -> datetime.datetime: ...
    @property
    def cycle_time(self) -> datetime.timedelta: ...
    @property
    def end(self) -> datetime.datetime: ...
    @property
    def lbs(self) -> float: ...
    @property
    def yds(self) -> float: ...
    def __repr__(self) -> str: ...