import datetime as dt
from app.support import HasID, SuperImmut, FloatRange
from app.schedule import Job

class Jet(HasID[str], SuperImmut):
    """
    A class for Jet objects.
    """
    n_ports: int
    port_range: FloatRange
    def __init__(self, id: str, n_ports: int, port_min: float, port_max: float,
                 min_date: dt.datetime, max_date: dt.datetime) -> None:
        ...
    @property
    def _prefix(self) -> str: ...
    @property
    def id(self) -> str: ...
    @property
    def last_job_end(self) -> dt.datetime: ...
    @property
    def rem_time(self) -> dt.timedelta: ...
    @property
    def jobs_since_strip(self) -> int: ...
    @property
    def soil_level(self) -> int: ...
    @property
    def jobs(self) -> list[Job]: ...
    def add_job(self, job: Job) -> None: ...
    def sort_jobs(self) -> None: ...