from typing import Iterator
import datetime
from app.support import HasID, FloatRange
from app.schedule.job import Job

class Jet(HasID[str]):
    def __init__(self, id: str, weekly_turns: float, n_ports: int,
                 port_range: FloatRange, start_date: datetime.datetime) -> None: ...
    @property
    def n_ports(self) -> int: ...
    @property
    def port_range(self) -> FloatRange: ...
    @property
    def avg_cycle(self) -> datetime.timedelta: ...
    @property
    def last_job_end(self) -> datetime.datetime: ...
    @property
    def rem_time(self) -> datetime.timedelta: ...
    def __iter__(self) -> Iterator[Job]: ...
    def add_job(self, job: Job) -> None: ...