class SuperImmut:
    def __init_subclass__(cls, attrs: tuple[str, ...] = tuple(),
                          priv_attrs: tuple[str, ...] = tuple(),
                          frozen: tuple[str, ...] = tuple()) -> None: ...
    def __init__(self, priv: dict[str], **kwargs) -> None: ...
    def __setattr__(self, name: str, value) -> None: ...