from typing import Callable

def setter_like[**P, T](func: Callable[P, T]) -> Callable[P, T]: ...

class SuperView[T]:
    def __init_subclass__(cls, attrs: tuple[str, ...] = tuple(), funcs: tuple[str, ...] = tuple(),
                          dunders: tuple[str, ...] = tuple()) -> None: ...
    def __init__(self, link: T) -> None: ...