from typing import Iterator
from app.support import HasID, SuperImmut
from app.style import FabricStyle, GreigeStyle, Color
from app.inventory import AllocRoll
from app.schedule.req import Req

class DyeLot(HasID[str], SuperImmut):
    """
    A class for DyeLot objects.
    """
    def __init__(self, req: Req) -> None:
        """Initialize a new DyeLot object with an associated requirement."""
        ...
    @property
    def _prefix(self) -> str: ...
    @property
    def id(self) -> str: ...
    @property
    def item(self) -> FabricStyle: ...
    @property
    def color(self) -> Color: ...
    @property
    def greige(self) -> GreigeStyle: ...
    @property
    def lbs(self) -> float: ...
    @property
    def yds(self) -> float: ...
    def __iter__(self) -> Iterator[AllocRoll]: ...
    def add_roll(self, roll: AllocRoll) -> None: ...