import datetime as dt
from app.support import HasID, SuperImmut, SuperView, Viewable
from app.style import GreigeStyle, Color, FabricStyle
from app.inventory import AllocRoll

class DyeLotView(SuperView['DyeLot']):
    start: dt.datetime
    end: dt.datetime
    rolls: tuple[AllocRoll, ...]
    item: FabricStyle
    @property
    def _prefix(self) -> str: ...
    @property
    def id(self) -> int: ...
    @property
    def greige(self) -> GreigeStyle: ...
    @property
    def color(self) -> Color: ...
    @property
    def lbs(self) -> float: ...
    @property
    def yds(self) -> float: ...

class DyeLot(HasID[int], Viewable[DyeLotView], SuperImmut):
    start: dt.datetime
    end: dt.datetime
    rolls: tuple[AllocRoll, ...]
    item: FabricStyle
    def __init__(self, start: dt.datetime, end: dt.datetime, rolls: list[AllocRoll],
                 item: FabricStyle) -> None: ...
    @property
    def _prefix(self) -> str: ...
    @property
    def id(self) -> int: ...
    @property
    def greige(self) -> GreigeStyle: ...
    @property
    def color(self) -> Color: ...
    @property
    def lbs(self) -> float: ...
    @property
    def yds(self) -> float: ...